import { Link } from "react-router-dom";

/**
 * Regulatory Positioning Overview
 * 
 * One-page memo format for board review, legal counsel, or regulatory inquiry.
 * Formal, institutional, precise, non-promotional.
 */

export default function Regulatory() {
  return (
    <div className="w-full bg-surface-primary print:bg-white">
      <div className="mx-auto max-w-3xl px-6 py-16 lg:px-12 lg:py-24 print:py-12">
        {/* Document Header */}
        <header className="border-b border-foreground/10 pb-8">
          <p className="text-xs font-medium uppercase tracking-[0.15em] text-foreground/50">
            Regulatory Positioning
          </p>
          <h1 className="mt-3 font-serif text-2xl font-medium tracking-[-0.02em] leading-[1.2] text-foreground sm:text-3xl">
            SettleRate — Regulatory Positioning Overview
          </h1>
        </header>

        {/* Document Body */}
        <article className="mt-10 space-y-8 text-[15px] leading-[1.85] text-foreground/70 sm:text-base">
          {/* Section 1: Platform Description */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Platform Description
            </h2>
            <p>
              SettleRate is an independent decision-support platform designed to help users model and understand potential mortgage outcomes. The platform provides analytical tools that allow users to compare mortgage structures using standardized, documented assumptions.
            </p>
          </section>

          {/* Section 2: Scope of Function */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Scope of Function
            </h2>
            <p>
              SettleRate's function is limited to illustrative modeling and comparative analysis. It does not originate loans, broker mortgage products, recommend specific financial products, provide personalized financial, legal, or tax advice, or participate in mortgage transactions.
            </p>
          </section>

          {/* Section 3: Separation from Incentive Structures */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Separation from Incentive Structures
            </h2>
            <p>
              SettleRate operates outside the mortgage incentive chain. It does not receive compensation from lenders, brokers, or affiliates, does not sell or share user data for referral purposes, and does not embed promotional or ranking logic within its outputs.
            </p>
          </section>

          {/* Section 4: Nature of Outputs */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Nature of Outputs
            </h2>
            <p>
              All outputs generated by SettleRate are illustrative and informational in nature. Calculations are based on user-provided and standardized assumptions and are intended to support understanding and discussion, not to direct or prescribe financial decisions.
            </p>
          </section>

          {/* Section 5: Intended Use */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Intended Use
            </h2>
            <p>
              SettleRate is designed to be used prior to or alongside engagement with licensed professionals. Advisors and lenders remain the sole source of professional judgment, guidance, and transactional execution.
            </p>
          </section>

          {/* Section 6: Regulatory Posture */}
          <section>
            <h2 className="mb-3 text-sm font-medium text-foreground">
              Regulatory Posture
            </h2>
            <p>
              By maintaining clear functional boundaries and avoiding transactional or advisory activity, SettleRate is positioned as analytical infrastructure rather than a regulated financial services provider.
            </p>
          </section>
        </article>

        {/* Document Footer */}
        <footer className="mt-12 border-t border-foreground/10 pt-8">
          <p className="text-xs text-foreground/40">
            Prepared for internal, partner, and regulatory review.
          </p>
          <p className="mt-4 print:hidden">
            <Link
              to="/approach"
              className="text-xs text-foreground/50 transition-colors hover:text-foreground"
            >
              Return to Approach
            </Link>
          </p>
        </footer>
      </div>
    </div>
  );
}
