/**
 * Terms of Service - Institutional, Regulator-Safe
 * 
 * These documents should read like infrastructure policy,
 * not startup compliance theater.
 */

export default function Terms() {
  return (
    <div className="mx-auto max-w-2xl">
      <article className="space-y-8">
        <header className="space-y-3">
          <h1 className="font-serif text-2xl font-normal tracking-tight sm:text-3xl">
            Terms of Service
          </h1>
          <p className="text-sm text-muted-foreground">
            Last updated: January 2025
          </p>
        </header>

        <div className="space-y-8 text-sm leading-relaxed text-muted-foreground">
          {/* Purpose and Scope - This sets the entire frame */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Purpose and Scope
            </h2>
            <p>
              SettleRate provides analytical tools for modeling mortgage scenarios 
              under standardized assumptions. The Service is designed to support 
              independent evaluation of mortgage structures and related financial 
              implications. SettleRate does not originate, broker, recommend, rank, 
              or refer mortgage products or providers.
            </p>
          </section>

          {/* No Advice; No Fiduciary Relationship */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              No Advice; No Fiduciary Relationship
            </h2>
            <p>
              The Service does not provide financial, legal, tax, or investment 
              advice. All outputs are analytical in nature and illustrative only. 
              Use of the Service does not create a fiduciary, advisory, or 
              professional relationship between SettleRate and any user.
            </p>
          </section>

          {/* User Responsibility */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              User Responsibility
            </h2>
            <p>
              Users are solely responsible for decisions made based on their 
              interpretation of outputs generated by the Service. Modeled outcomes 
              are based on stated assumptions and do not guarantee actual loan 
              terms, approval, pricing, or future results.
            </p>
          </section>

          {/* Independence and Non-Affiliation */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Independence and Non-Affiliation
            </h2>
            <p>
              SettleRate operates independently of lenders, brokers, originators, 
              and financial institutions. SettleRate does not receive compensation 
              based on user selections, loan outcomes, or transactions.
            </p>
          </section>

          {/* Use of Outputs */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Use of Outputs
            </h2>
            <p>
              Outputs generated by the Service may be used for personal reference, 
              advisor discussion, and professional review. Outputs may not be 
              represented as recommendations, endorsements, or guarantees by 
              SettleRate.
            </p>
          </section>

          {/* Limitations of Modeling */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Limitations of Modeling
            </h2>
            <p>
              Mortgage modeling involves assumptions regarding rates, taxes, 
              insurance, and other variables that may change over time. SettleRate 
              does not warrant the accuracy or completeness of any output beyond 
              the assumptions disclosed at the time of generation.
            </p>
          </section>

          {/* Account Responsibilities */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Account Responsibilities
            </h2>
            <p>
              You are responsible for maintaining the security of your account and 
              for all activities that occur under your account. Notify us 
              immediately of any unauthorized use.
            </p>
          </section>

          {/* Intellectual Property */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Intellectual Property
            </h2>
            <p>
              All software, models, methodologies, and presentation formats used by 
              the Service are the intellectual property of SettleRate and may not be 
              reproduced, reverse-engineered, or redistributed except as expressly 
              permitted.
            </p>
          </section>

          {/* Acceptable Use */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="list-inside list-disc space-y-1">
              <li>Use the Service for any illegal purpose</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Resell or redistribute the Service without permission</li>
              <li>Represent outputs as official recommendations or guarantees</li>
            </ul>
          </section>

          {/* Subscription and Billing */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Subscription and Billing
            </h2>
            <p>
              Paid subscriptions are billed monthly or annually. You may cancel at 
              any time, and your access will continue until the end of your current 
              billing period. Refunds are provided at our discretion.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, SettleRate shall not be liable 
              for any indirect, incidental, consequential, or financial damages 
              arising from use of the Service or reliance on its outputs.
            </p>
          </section>

          {/* Governing Law */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Governing Law
            </h2>
            <p>
              These Terms shall be governed by and construed in accordance with the 
              laws of the State of Delaware, without regard to its conflict of law 
              provisions.
            </p>
          </section>

          {/* Changes to Terms */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">
              Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. Continued use of the 
              Service after changes constitutes acceptance of the new terms.
            </p>
          </section>

          {/* Contact */}
          <section className="space-y-3">
            <h2 className="text-base font-medium text-foreground">Contact</h2>
            <p>
              Questions about these terms? Contact us at{" "}
              <a
                href="mailto:legal@settlerate.com"
                className="text-foreground underline underline-offset-2"
              >
                legal@settlerate.com
              </a>
              .
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}
