// This file is automatically generated. Do not edit it directly.
// Exceptions:
// 1. Auth storage must be environment-safe for Node/Vitest CI imports.
// 2. Fail-fast validation of public client env vars (Phase 8.1 Epic 2,
//    ADR 0002) replaces @supabase/supabase-js's generic
//    "supabaseUrl is required." error with an actionable one.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { validateClientEnv } from '@/lib/clientEnv';

const {
  supabaseUrl: SUPABASE_URL,
  supabasePublishableKey: SUPABASE_PUBLISHABLE_KEY,
} = validateClientEnv({
  VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
  VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
});

/**
 * Use browser localStorage when available. In Node (Vitest/CI), omit storage so
 * @supabase/auth-js falls back to its in-memory adapter — do not reference the
 * bare `localStorage` global, which throws ReferenceError outside browsers.
 */
const authStorage =
  typeof window !== "undefined" && window.localStorage
    ? window.localStorage
    : undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    ...(authStorage ? { storage: authStorage } : {}),
    // Keep session persistence enabled; browser uses localStorage, Node uses
    // auth-js memory storage for the process lifetime only.
    persistSession: true,
    autoRefreshToken: true,
  }
});
